---
title: "Low salt Vs Control"
author: "jeff karnsomprot"
date: "2025-06-29"
output:
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: yes
    theme: journal
    df_print: paged
    code_folding: hide
    highlight: pygments
---

# Loading in Data sets + Library packages.

```{r load new packages, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

options(repos = c(CRAN = "https://cloud.r-project.org"))
if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!requireNamespace('BiocManager', quietly = TRUE)) {install.packages('BiocManager'); require("BiocManager")}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("stringr")) {install.packages("stringr"); require("stringr")}
if (!require("Seurat")) {install.packages("Seurat"); require("Seurat")}
if (!require("sctransform")) {install.packages("sctransform"); require("sctransform")}
if (!require("glmGamPoi")) {BiocManager::install('glmGamPoi'); require("glmGamPoi")}
if (!require("patchwork")) {install.packages("patchwork"); require("patchwork")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("EnhancedVolcano")) {BiocManager::install('EnhancedVolcano'); require("EnhancedVolcano")}
if (!require("DESeq2")) {BiocManager::install('DESeq2'); require("DESeq2")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")}
if (!require("RColorBrewer")) {install.packages("RColorBrewer"); require("RColorBrewer")}
if (!require("car")) {install.packages("car"); require("car")}
if (!require("openxlsx")) {install.packages("openxlsx"); require("openxlsx")}
if (!require("readxl")) {install.packages("readxl"); require("readxl")}
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")}
if (!require("gghighlight")) {install.packages("gghighlight"); require("gghighlight")}
if (!require("ggpmisc")) {install.packages("ggpmisc"); require("ggpmisc")}
if (!require("data.table")) {install.packages("data.table"); require("data.table")}
if (!require("here")) {install.packages("here"); require("here")}
if (!require("clusterProfiler")) {BiocManager::install('clusterProfiler'); require("clusterProfiler")}
if (!require("enrichplot")) {BiocManager::install('enrichplot'); require("enrichplot")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")} # for data frame transformation
if (!require("gplots")) {install.packages("gplots"); require("gplots")}
if (!require("ggvenn")) {install.packages("ggvenn"); require("ggvenn")}
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")}

# Install from scratch
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("RSQLite")  # Core dependency
BiocManager::install("org.Mm.eg.db")
BiocManager::install("clusterProfiler")


# CRAN packages
install.packages(c("dplyr", "magrittr"))
library(org.Mm.eg.db)
library(clusterProfiler)
library(AnnotationDbi)
library(dplyr)
library(magrittr)




library("EnhancedVolcano")
library(UpSetR)

```


# Loading Dataset

```{r}
options(future.globals.maxSize = 74 * 1024^3) # 55 GB
getOption("future.globals.maxSize") #59055800320
```

```{r}

load(here("jk_code", "SO4analysis.rds"))
```


```{r}


VlnPlot(SO4,"S100g",split.by = "treatment",group.by = "sample")

# Macula Densa Markers , Nos1, Avpr1a, Slc12a1, Ptgs2, and Slc9a2

VlnPlot(SO4, c("Nos1","Avpr1a","Slc12a1","Ptgs2","Slc9a2"),split.by = "treatment",group.by = "treatment")

DimPlot(SO4)

SO4 <- SO4[
  !grepl("^(mt-|Rp|Gm)|Rik$", rownames(SO4)),
  ,
  drop = FALSE
]

DimPlot(SO4,group.by = "treatment",split.by = "treatment")

#compare each type 1 control to type 1 low_treatment

```
 # Markers of control vs low_salt up/down regulation
```{r}

type_markers <- FindMarkers(
  object = SO4,
  ident.1 = "low_salt",   
  ident.2 = "control",     
  group.by = "treatment",
  min.pct = 0.1,           
  logfc.threshold = 0.25,  
  only.pos = FALSE         
)

```


# top 20 genes shown by treatment groups

```{r}

df3 <- type_markers %>%
  arrange(desc(avg_log2FC)) %>%
  head(15)

df3 <- rownames(df3)

df <- AverageExpression(
  object = SO4,
  features = df3,
  group.by = 'treatment'
)$RNA

df

df <- as.data.frame(df)

df <- t(scale(t(df)))

# convert df to tidy format

df_tidy <- df %>%
  as.data.frame() %>%
  rownames_to_column(var = "Gene") %>%
  pivot_longer(cols = -Gene, names_to = "treatment", values_to = "Expression")
               
# Graph with geom_tile

df_tidy$treatment <- factor(df_tidy$treatment, levels = c("control","low_salt"))

f4 <- ggplot(df_tidy, aes(x = treatment, y = Gene, fill = Expression)) +
  geom_tile(color = "black", size = 0.2, width = 0.97, height = 0.90) +  # Adds thin border and spacing between tiles
  scale_fill_distiller(palette = "RdYlBu") +
  theme_minimal() +
  theme(
    axis.text = element_text(size = 12, color = "black"),
    axis.title = element_text(size = 14),
    axis.ticks = element_blank(),         # Removes tick marks
    panel.grid = element_blank(),          # Removes grid lines
    legend.position = "bottom",            # Centers the legend below the plot
    legend.title = element_text(size = 14), # Increases legend title size
    legend.text = element_text(size = 12)   # Increases legend text size
  ) +
  labs(x = "Cell Type", y = "Gene", fill = "Relative Expression")

f4

```
# top 20 genes shown by samples

```{r}


df3 <- type_markers %>%
  arrange(desc(avg_log2FC)) %>%
  head(15)

df3 <- rownames(df3)

df <- AverageExpression(
  object = SO4,
  features = df3,
  group.by = 'sample'
)$RNA

df

df <- as.data.frame(df)

df <- t(scale(t(df)))

# convert df to tidy format

df_tidy <- df %>%
  as.data.frame() %>%
  rownames_to_column(var = "Gene") %>%
  pivot_longer(cols = -Gene, names_to = "sample", values_to = "Expression")
               
# Graph with geom_tile

df_tidy$sample <- factor(df_tidy$sample, levels = c("SO1","SO2","SO3","SO4"))

f4 <- ggplot(df_tidy, aes(x = sample, y = Gene, fill = Expression)) +
  geom_tile(color = "black", size = 0.2, width = 0.97, height = 0.90) +  # Adds thin border and spacing between tiles
  scale_fill_distiller(palette = "RdYlBu") +
  theme_minimal() +
  theme(
    axis.text = element_text(size = 12, color = "black"),
    axis.title = element_text(size = 14),
    axis.ticks = element_blank(),         # Removes tick marks
    panel.grid = element_blank(),          # Removes grid lines
    legend.position = "bottom",            # Centers the legend below the plot
    legend.title = element_text(size = 14), # Increases legend title size
    legend.text = element_text(size = 12)   # Increases legend text size
  ) +
  labs(x = "Cell Type", y = "Gene", fill = "Relative Expression")

f4

```

# HeatMap of each clusters top genes from pathway analysis

```{r}


genes123 <- c("Pappa2","Mcub","Ptgs2","Aard","Egf", "Umod", "Cldn19", "Foxq1", "Jun", "Fos", 
              "Socs3", "Hspb1", "Dusp1", "Trib1", "Cxcl10", 
              "Isg15", "Ifit1")

DoHeatmap(SO4,features = genes123)

```
# Proportional Plot

```{r}


# Change the code to use the right Seurat Object and column that separates by treatment group.

 Idents(SO4) <- "subclass_MD"

t1 <- table(Idents(SO4), SO4$treatment)[, c("control", "low_salt")]

t1

 

prop.t1 <- prop.table(t1, margin = 2)

prop.t1

 

t2 <- as.data.frame(t1)

colnames(t2) <- c('Cell_type', 'Treatment', 'Frequency')

 

# Original plot

 

ggplot(t2, aes(fill=Cell_type, y=Frequency, x= Treatment)) +

  geom_bar(position="fill", stat = "identity", fun.y = "mean", colour="black") +

  theme_classic()

```


```{r}



# Change the code to use the right Seurat Object and column that separates by treatment group.

 Idents(SO4) <- "subclass_MD"

t1 <- table(Idents(SO4), SO4$sample)[, c("SO1", "SO2","SO3","SO4")]

t1

 

prop.t1 <- prop.table(t1, margin = 2)

prop.t1

 

t2 <- as.data.frame(t1)

colnames(t2) <- c('Cell_type', 'sample', 'Frequency')

 

# Original plot

 

ggplot(t2, aes(fill=Cell_type, y=Frequency, x= sample)) +

  geom_bar(position="fill", stat = "identity", fun.y = "mean", colour="black") +

  theme_classic()

```
