---
title: "Quality Control"
author: "jeff karnsomprot"
date: "2025-06-05"
output:
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: yes
    theme: journal
    df_print: paged
    code_folding: hide
    highlight: pygments
---

# Objective

The goal of this session is to get a clean macula densa dataset to work with.

# Load Packages
```{r load new packages, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("Seurat")) {install.packages("Seurat"); require("Seurat")}
if (!require("patchwork")) {install.packages("patchwork"); require("patchwork")}
if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("BiocManager")) {install.packages("BiocManager"); require("BiocManager")}
if (!require("tibble")) {install.packages("tibble"); require("tibble")}
if (!require("ggpmisc")) {install.packages("ggpmisc"); require("ggpmisc")}
if (!require("RColorBrewer")) {install.packages("RColorBrewer"); require("RColorBrewer")} #color
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")}
if (!require("DESeq2")) {BiocManager::install('DESeq2'); require("DESeq2")}
if (!require("here")) {install.packages("here"); require("here")}
if (!require("stringr")) {install.packages("stringr"); require("stringr")}
if (!require("car")) {install.packages("car"); require("car")}
if (!require("openxlsx")) {install.packages("openxlsx"); require("openxlsx")}
if (!require("readxl")) {install.packages("readxl"); require("readxl")}
if (!require("data.table")) {install.packages("data.table"); require("data.table")}
if (!require("ggvenn")) {install.packages("ggvenn"); require("ggvenn")}
if (!require("kableExtra")) {install.packages("kableExtra"); require("kableExtra")} # for color brewer
if (!require("gplots")) {install.packages("gplots"); require("gplots")} # for color brewer
if (!require("clusterProfiler")) {BiocManager::install('clusterProfiler'); require("clusterProfiler")}
if (!require("enrichplot")) {BiocManager::install('enrichplot'); require("enrichplot")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")} # for data frame transformation
if (!require("plotly")) {install.packages("plotly"); require("plotly")}
library("EnhancedVolcano")



```


```{r}
options(future.globals.maxSize = 74 * 1024^3) # 55 GB
getOption("future.globals.maxSize") #59055800320
```

# Load Dataset
``` {r}

SO1 <- LoadSeuratRds(here("outputs", "so_merge_raw.rds"))


head(SO1@meta.data)
```

# Subset out non MD cells. 

```{r}

SO2 <- subset(SO1, idents = c("4", "5", "6", "7"), invert = TRUE)

SO3 <- subset(SO2, features = grep("^mt-|^Gm|Rik|^Rp", rownames(SO2), invert = TRUE, value = TRUE))

DimPlot(SO2)

SO3 <- SCTransform(SO3) %>%
    RunPCA() %>%
    FindNeighbors(dims = 1:15) %>%
    FindClusters(resolution = 2) %>%
    RunUMAP(dims = 1:15)

DimPlot(SO3)

DimPlot(SO3,split.by = "treatment")

markers.to.plot1 <- c("Lrp2",         # PT
                      "Slc5a12",      # PT-S1
                      "Slc13a3",      # PT-S2
                      "Slc16a9",      # PT-S3
                      "Havcr1",       # Injured PT
                      "Epha7",        # dTL
                      "Cryab",        # dTL
                      "Cdh13",        # dTL1
                      "Slc14a2",      # dTL2
                      "Slc12a1",      # TAL
                      "Umod",         # TAL, DCT1
                      "Egf",          # TAL, DCT1,
                      "Cldn10",       # TAL
                      "Cldn16",       # TAL
                      "Nos1",         # MD
                      "Slc12a3",      # DCT
                      "Pvalb",        # DCT1
                      "Slc8a1",       # DCT2, CNT
                      "Aqp2",         # PC
                      "Slc4a1",       # IC-A
                      "Slc26a4",      # IC-B
                      "Nphs1",        # Podo
                      "Ncam1",        # PEC
                      "Flt1",         # Endo
                      "Emcn",         # Glom Endo
                      "Kdr",          # Capillary Endo
                      "Pdgfrb",       # Perivascular
                      "Pdgfra",       # Fib
                      "Piezo2",       # Mesangial
                      "Acta2",        # Mural
                      "Ptprc",        # Immune
                      "Cd74",         # Macrophage
                      "Skap1",        # B/T Cells 
                      "Upk1b",        # Uro
                      "Top2a"         # Proliferation
)

DotPlot(SO3,
features = markers.to.plot1,
dot.scale = 8,
dot.min = 0,
scale = FALSE,
scale.max = 100,
scale.min = 0,
col.min = -2.5,
col.max = 2.5)+
coord_flip()



head(SO3)


```


```{r}


SO4 <- subset(SO3, idents = c("23"), invert = TRUE)

DimPlot(SO4)

SO4 <- SCTransform(SO4) %>%
    RunPCA() %>%
    FindNeighbors(dims = 1:16) %>%
    FindClusters(resolution = 2) %>%
    RunUMAP(dims = 1:16)

DimPlot(SO4)
DimPlot(SO4,split.by = "treatment")

SO4@meta.data$seurat_clusters <- factor(
  SO4@meta.data$seurat_clusters,
  levels = c("0", "1", "2", "3", "4", "6", "8", "9", "10", "12", "15", "22", "18", 
             "19", "21", "16", "13", "20", "23", "17", "14", "5", "7", "11", "24", "25")
)


Idents(SO4) <- SO4$seurat_clusters


## Simplifying into a few types

markers.to.plot2 <- c("Pappa2",
                      "Nos1",
                      "Egf",
                      "Umod",
                      "Fos",
                      "Junb",
                      "Cxcl10",
                      "Isg15",
                       "Sult1d1",
                      "Cldn19",
                      "Foxq1"
)

DimPlot(SO4)

DotPlot(SO4,
features = markers.to.plot2,
dot.scale = 8,
dot.min = 0,
scale = FALSE,
scale.max = 100,
scale.min = 0,
col.min = -2.5,
group.by = "seurat_clusters",
col.max = 2.5)+
coord_flip()


```


```{r}
Idents(SO4) <- "seurat_clusters"

all_markers <- FindAllMarkers(SO4, only.pos = TRUE, min.pct = 0.5, logfc.threshold = 0.5)

all_markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1, p_val_adj < 0.05) %>%
    slice_head(n = 3) %>%
    ungroup() -> top3

DoHeatmap(SO4, features = top3$gene) + NoLegend()


```

# Assigning Subclasses for clusters

```{r}


SO4@meta.data <- SO4@meta.data %>%
  mutate(subclass_MD = dplyr::case_when(
    seurat_clusters %in% c(0,1,2,4,6,10,21,18,19,12,22) ~ "type_1a",
     seurat_clusters %in% c(3,9,15,21,8) ~ "type_1b",
    seurat_clusters %in% c(7,24,25,5,11) ~ "type_2a",
    seurat_clusters %in% c(14,17) ~ "type_2b",
      seurat_clusters %in% c(16,13) ~ "type_3a",
    seurat_clusters %in% c(20) ~ "type_3b",
    seurat_clusters == 23 ~ "type_4",
  ))


SO4@meta.data$subclass_MD <- factor(
  SO4@meta.data$subclass_MD, 
  levels = c("type_1a","type_1b", "type_2a", "type_2b","type_3a","type_3b","type_4")
)


SO4@meta.data <- SO4@meta.data %>%
  mutate(subclass2_MD = dplyr::case_when(
    seurat_clusters %in% c(0,1,2,3,4,6,8,9,10,21,15,22,18,19,21,12) ~ "type_1",
    seurat_clusters %in% c(7,24,25,5,11,14,17) ~ "type_2",
    seurat_clusters %in% c(16,13,20) ~ "type_3",
    seurat_clusters %in% c(23) ~ "type_4"
    
  ))

SO4@meta.data$subclass2_MD <- factor(
  SO4@meta.data$subclass2_MD, 
  levels = c("type_1", "type_2","type_3","type_4")
)

Idents(SO4) <- SO4@meta.data$subclass_MD

DimPlot(object = SO4, reduction = "umap", group.by = "subclass_MD", label = TRUE)
DimPlot(object = SO4, reduction = "umap", group.by = "subclass2_MD", label = TRUE)
DimPlot(SO4,group.by = "subclass2_MD",split.by = "treatment")
DimPlot(SO4,group.by = "seurat_clusters",split.by = "treatment")

library(plotly)

dim_plot <- DimPlot(SO4, reduction = "umap",group.by = "seurat_clusters") +
  ggtitle("UMAP Dimensional Reduction")
interactive_plot <- ggplotly(dim_plot)

# Display the interactive plot
interactive_plot


```

```{r}

# Assign your markers as a vector
genes_to_plot <- c(
  "Fos", "Socs3", "Gadd45b", "Wee1", "Hspa1a", "Sat1", # TYPE 3
  "Cxcl12", "Itpr2", "Bmp4", "Casr", "Grin2c", "Irx3", "Rap1gap", "App", "Wwc1", # TYPE 2
  "Syt5", "Syn3", "Cacna1d", "Slc6a7", "Robo2", "Begain", # TYPE 1
  "Pappa1", "Nos1", "Ptgs2", "Bmp2", "Atp2a3" # SUBCLUSTERS within type 1
)

DoHeatmap(SO4, features = genes_to_plot, group.by = "seurat_clusters")

```

# Viewing genes that differentiate each Type

```{r}

markers.to.plot3 <- c("Pappa2",
                      "Egf",
                      "Umod",
                      "Fos",
                      "Junb",
                      "Cxcl10",
                      "Isg15"
)


DotPlot(SO4,
features = markers.to.plot3,
dot.scale = 8,
dot.min = 0,
scale = FALSE,
scale.max = 100,
scale.min = 0,
col.min = -2.5,
group.by = "subclass2_MD",
col.max = 2.5)+
coord_flip()

DotPlot(SO4,
features = markers.to.plot2,
dot.scale = 8,
dot.min = 0,
scale = FALSE,
scale.max = 100,
scale.min = 0,
col.min = -2.5,
group.by = "subclass_MD",
col.max = 2.5)+
coord_flip()



```

```{r}

Idents(SO4) <- "seurat_clusters"

all_markers <- FindAllMarkers(SO4, only.pos = TRUE, min.pct = 0.5, logfc.threshold = 0.5)

 

# Order by avg_log2FC

all_markers <- all_markers %>%

  arrange(desc(avg_log2FC)) %>%

  select(gene, everything())

 

# Split by cluster (ident column)

marker_list <- split(all_markers, all_markers$cluster)

 

# Sort names alphanumerically

sorted_cluster_names <- names(marker_list)[order(as.numeric(names(marker_list)))]

 

# Create a workbook

wb <- createWorkbook()

 

# Add each cluster as a new worksheet

for (cluster_name in sorted_cluster_names) {

  addWorksheet(wb, sheetName = cluster_name)

  writeData(wb, sheet = cluster_name, marker_list[[cluster_name]])

}

 

date <- format(Sys.Date(), "%Y%m%d")

 

# Save workbook

saveWorkbook(wb, here("jk_code", paste0(date, "_", "_SO4_FindAllMarkers_By_Cluster.xlsx")), overwrite = TRUE)

# Saving Seurat Object

save(SO4, file = here("jk_code", "JK_clean_MD.rds"))


```


```{r}

all_markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1, p_val_adj < 0.05) %>%
    slice_head(n = 3) %>%
    ungroup() -> top3

DoHeatmap(SO4, features = top3$gene) + NoLegend()

```
