---
title: "Upset Plot Analysis"
author: "jeff karnsomprot"
date: "2025-07-15"
output:
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: yes
    theme: journal
    df_print: paged
    code_folding: hide
    highlight: pygments
---



# analysis of expression between samples (upset genes)

## Type 1

### Type 1 Pathway Upregulated = Low salt 

```{r}

df2<- type1markers%>% arrange(desc(avg_log2FC))

DEG_list <- df2

markers1up <- DEG_list %>% rownames_to_column(var="SYMBOL")


ENTREZ_list <- bitr(
  geneID = rownames(DEG_list),
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Mm.eg.db
)

markers1up <-  ENTREZ_list %>% inner_join(markers1up, by = "SYMBOL")

#markers1up <-  markers1up %>% dplyr::filter(p_val_adj < 0.05)
#head(markers, n = 50)

pos.markers1up <-  markers1up %>% dplyr::filter(avg_log2FC > 0) %>%  arrange(desc(abs(avg_log2FC)))
#change around avg log value 

pos.ranks1up <- pos.markers1up$ENTREZID[abs(pos.markers1up$avg_log2FC) > 0]
#head(pos.ranks)

pos_go1up <- enrichGO(gene = pos.ranks1up,           #a vector of entrez gene id
                   OrgDb = "org.Mm.eg.db",    
                   ont = "BP",
                   readable = TRUE)              #whether mapping gene ID to gene Name

pos_go1up

 chart1up <- dotplot(pos_go1up) +
    ggtitle("type 1 upregulated lowsalt") +
    theme_classic() + 
    theme(
        plot.title = element_text(hjust = 0.5),
        legend.position = "left",
        axis.text.y = element_text(hjust = 0, size = 10)) +
    scale_y_discrete(position = "right", 
                     labels = function(x) str_wrap(x, width = 25))  # Wrap y-axis labels to 2 lines
 

chart1up

```
### Type 1 Pathway Downregulated

```{r}
df2 <- type1markers %>% arrange(desc(avg_log2FC))

DEG_list <- df2

markers1down <- DEG_list %>% rownames_to_column(var="SYMBOL")

ENTREZ_list <- bitr(
  geneID = rownames(DEG_list),
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Mm.eg.db
)

markers1down <- ENTREZ_list %>% inner_join(markers1down, by = "SYMBOL")


pos.markers1down <- markers1down %>% dplyr::filter(avg_log2FC < 0) %>% arrange(desc(abs(avg_log2FC)))
#change around avg log value 

pos.ranks1down <- pos.markers1down$ENTREZID[abs(pos.markers1down$avg_log2FC) > 0]
#head(pos.ranks2up)

pos_go1down <- enrichGO(gene = pos.ranks1down,           #a vector of entrez gene id
                   OrgDb = "org.Mm.eg.db",    
                   ont = "BP",
                   readable = TRUE)              #whether mapping gene ID to gene Name

pos_go1down

chart1down <- dotplot(pos_go1down) +
    ggtitle("type 2 downregulated control") +
    theme_classic() + 
    theme(
        plot.title = element_text(hjust = 0.5),
        legend.position = "left",
        axis.text.y = element_text(hjust = 0, size = 10)) +
    scale_y_discrete(position = "right", 
                     labels = function(x) str_wrap(x, width = 25))  # Wrap y-axis labels to 2 lines

chart1down

```

## Type 2 
### Type 2 Pathway Upregulated

```{r}



```

### Type 2 Pathway Down regulated = Control

## Type 3 

### Type 3 Pathway Down regulated = Control

```{r}

df2 <- type3markers %>% arrange(desc(avg_log2FC))

#df2 <- df %>% filter(p_val_adj < 0.05)

DEG_list <- df2

markers2up <- DEG_list %>% rownames_to_column(var="SYMBOL")

ENTREZ_list <- bitr(
  geneID = rownames(DEG_list),
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Mm.eg.db
)

markers2up <- ENTREZ_list %>% inner_join(markers2up, by = "SYMBOL")

#markers2up <- markers2up %>% dplyr::filter(p_val_adj < 0.05)
#head(markers2up, n = 50)

pos.markers2up <- markers2up %>% dplyr::filter(avg_log2FC > 0.2) %>% arrange(desc(abs(avg_log2FC)))
#change around avg log value 

pos.ranks2up <- pos.markers2up$ENTREZID[abs(pos.markers2up$avg_log2FC) > 0]
#head(pos.ranks2up)

pos_go2up <- enrichGO(gene = pos.ranks2up,           #a vector of entrez gene id
                   OrgDb = "org.Mm.eg.db",    
                   ont = "BP",
                   readable = TRUE)              #whether mapping gene ID to gene Name

pos_go2up

chart3down <- dotplot(pos_go2up) +
    ggtitle("type 3 downregulated control") +
    theme_classic() + 
    theme(
        plot.title = element_text(hjust = 0.5),
        legend.position = "left",
        axis.text.y = element_text(hjust = 0, size = 10)) +
    scale_y_discrete(position = "right", 
                     labels = function(x) str_wrap(x, width = 25))  # Wrap y-axis labels to 2 lines

chart3down

```


## Type 4

### Type 4  Downregulated = control, negative, supressed of low_salt

```{r}


# Arrange and filter DEGs for type 4
df2 <- type4markers %>% arrange(desc(avg_log2FC))

#df2 <- df %>% filter(p_val_adj < 0.05)

DEG_list <- df2

markers4down <- DEG_list %>% rownames_to_column(var="SYMBOL")

ENTREZ_list <- bitr(
  geneID = rownames(DEG_list),
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Mm.eg.db
)

markers4down <- ENTREZ_list %>% inner_join(markers4down, by = "SYMBOL")

#markers4down <- markers4down %>% dplyr::filter(p_val_adj < 0.05)
#head(markers4down, n = 50)

pos.markers4down <- markers4down %>% dplyr::filter(avg_log2FC > 0) %>% arrange(desc(abs(avg_log2FC)))
# Adjust avg_log2FC threshold here if you want a stricter cutoff

pos.ranks4down <- pos.markers4down$ENTREZID[abs(pos.markers4down$avg_log2FC) > 0]
#head(pos.ranks4down)

pos_go4down <- enrichGO(
  gene = pos.ranks4down,           # a vector of entrez gene id
  OrgDb = org.Mm.eg.db,    
  ont = "BP",
  readable = TRUE                  # whether mapping gene ID to gene Name
)

pos_go4down

chart4down <- dotplot(pos_go4down) +
  ggtitle("type 4  Downregulated = control, negative, supressed of low_salt") +
  theme_classic() + 
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "left",
    axis.text.y = element_text(hjust = 0, size = 10)
  ) +
  scale_y_discrete(
    position = "right", 
    labels = function(x) str_wrap(x, width = 25)
  )  # Wrap y-axis labels to 2 lines

chart4down

```


### Type 4  Downregulated = control, negative, supressed of low_salt

```{r}


# Arrange and filter DEGs for type 4
df2 <- allmarkers %>% arrange(desc(avg_log2FC))

#df2 <- df %>% filter(p_val_adj < 0.05)

DEG_list <- df2

markers4down <- DEG_list %>% rownames_to_column(var="SYMBOL")

ENTREZ_list <- bitr(
  geneID = rownames(DEG_list),
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Mm.eg.db
)

markers4down <- ENTREZ_list %>% inner_join(markers4down, by = "SYMBOL")

#markers4down <- markers4down %>% dplyr::filter(p_val_adj < 0.05)
#head(markers4down, n = 50)

pos.markers4down <- markers4down %>% dplyr::filter(avg_log2FC > 0.5) %>% arrange(desc(abs(avg_log2FC)))
# Adjust avg_log2FC threshold here if you want a stricter cutoff

pos.ranks4down <- pos.markers4down$ENTREZID[abs(pos.markers4down$avg_log2FC) > 0]
#head(pos.ranks4down)

pos_go4down <- enrichGO(
  gene = pos.ranks4down,           # a vector of entrez gene id
  OrgDb = org.Mm.eg.db,    
  ont = "BP",
  readable = TRUE                  # whether mapping gene ID to gene Name
)

pos_go4down

chart4down <- dotplot(pos_go4down) +
  ggtitle("type 4  Downregulated = control, negative, supressed of low_salt") +
  theme_classic() + 
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "left",
    axis.text.y = element_text(hjust = 0, size = 10)
  ) +
  scale_y_discrete(
    position = "right", 
    labels = function(x) str_wrap(x, width = 25)
  )  # Wrap y-axis labels to 2 lines

chart4down

```

```{r}


# Arrange and filter DEGs for type 4
df2 <- allmarkers %>% arrange(desc(avg_log2FC))

#df2 <- df %>% filter(p_val_adj < 0.05)

DEG_list <- df2

markers4down <- DEG_list %>% rownames_to_column(var="SYMBOL")

ENTREZ_list <- bitr(
  geneID = rownames(DEG_list),
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Mm.eg.db
)

markers4down <- ENTREZ_list %>% inner_join(markers4down, by = "SYMBOL")

#markers4down <- markers4down %>% dplyr::filter(p_val_adj < 0.05)
#head(markers4down, n = 50)

pos.markers4down <- markers4down %>% dplyr::filter(avg_log2FC < 0 ) %>% arrange(desc(abs(avg_log2FC)))
# Adjust avg_log2FC threshold here if you want a stricter cutoff

pos.ranks4down <- pos.markers4down$ENTREZID[abs(pos.markers4down$avg_log2FC) > 0]
#head(pos.ranks4down)

pos_go4down <- enrichGO(
  gene = pos.ranks4down,           # a vector of entrez gene id
  OrgDb = org.Mm.eg.db,    
  ont = "BP",
  readable = TRUE                  # whether mapping gene ID to gene Name
)

pos_go4down

chart4down <- dotplot(pos_go4down) +
  ggtitle("type 4  Downregulated = control, negative, supressed of low_salt") +
  theme_classic() + 
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "left",
    axis.text.y = element_text(hjust = 0, size = 10)
  ) +
  scale_y_discrete(
    position = "right", 
    labels = function(x) str_wrap(x, width = 25)
  )  # Wrap y-axis labels to 2 lines

chart4down

```