---
title: "removing mt Rp Gm"
author: "jeff karnsomprot"
date: "2025-06-11"
output:
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: yes
    theme: journal
    df_print: paged
    code_folding: hide
    highlight: pygments
---

# Loading Packages + Data

```{r load new packages, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("Seurat")) {install.packages("Seurat"); require("Seurat")}
if (!require("patchwork")) {install.packages("patchwork"); require("patchwork")}
if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("BiocManager")) {install.packages("BiocManager"); require("BiocManager")}
if (!require("tibble")) {install.packages("tibble"); require("tibble")}
if (!require("ggpmisc")) {install.packages("ggpmisc"); require("ggpmisc")}
if (!require("RColorBrewer")) {install.packages("RColorBrewer"); require("RColorBrewer")} #color
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")}
if (!require("DESeq2")) {BiocManager::install('DESeq2'); require("DESeq2")}
if (!require("here")) {install.packages("here"); require("here")}
if (!require("stringr")) {install.packages("stringr"); require("stringr")}
if (!require("car")) {install.packages("car"); require("car")}
if (!require("openxlsx")) {install.packages("openxlsx"); require("openxlsx")}
if (!require("readxl")) {install.packages("readxl"); require("readxl")}
if (!require("data.table")) {install.packages("data.table"); require("data.table")}
if (!require("ggvenn")) {install.packages("ggvenn"); require("ggvenn")}
if (!require("kableExtra")) {install.packages("kableExtra"); require("kableExtra")} # for color brewer
if (!require("gplots")) {install.packages("gplots"); require("gplots")} # for color brewer
if (!require("clusterProfiler")) {BiocManager::install('clusterProfiler'); require("clusterProfiler")}
if (!require("enrichplot")) {BiocManager::install('enrichplot'); require("enrichplot")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")} # for data frame transformation
if (!require("plotly")) {install.packages("plotly"); require("plotly")}
library("EnhancedVolcano")


```

```{r}


load(here("jk_code", "JK_cleanMD.rds"))

```

# Removing mt, Rp, Gm genes
```{r}


SO4 <- subset(SO4, features = grep("^mt-|^Rp|^Gm", rownames(SO4), invert = TRUE, value = TRUE))

```

```{r}
ElbowPlot(SO4)
SO4 <- SCTransform(SO4) %>%
    RunPCA() %>%
    FindNeighbors(dims = 1:27) %>%
    FindClusters(resolution = 0.16) %>%
    RunUMAP(dims = 1:27)

DimPlot(SO4)
DimPlot(SO4,split.by = "sample")
DimPlot(SO4,split.by = "treatment")

SO.markers <- FindAllMarkers(SO4, only.pos = TRUE)
SO.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1)

SO.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10

DoHeatmap(SO4, features = top10$gene) + NoLegend()
DimPlot(SO4)
DimPlot(SO4,split.by = "sample")


```


```{r}
SO4@meta.data <- SO4@meta.data %>% 
  mutate(subclass_MD = dplyr::case_when(
    seurat_clusters == 0  ~ "type_1",
    seurat_clusters == 1  ~ "type_2",
    seurat_clusters == 2  ~ "type_3",
    seurat_clusters == 3  ~ "type_4",
    seurat_clusters == 4  ~ "type_5",
  

  ))

SO4@meta.data$subclass_MD <- factor(SO4@meta.data$subclass_MD , levels = c("type_1", "type_2", "type_3", "type_4","type_5"))

Idents(SO4) <- SO4@meta.data$subclass_MD

DimPlot(object = SO4, reduction = "umap", group.by = "subclass_MD", label = TRUE)


DimPlot(object = SO4, reduction = "umap", label = TRUE)

Idents(SO4) <- "subclass_MD"

DimPlot(SO4,split.by = "sample",group.by = "seurat_clusters")

```

```{r}

DoHeatmap(SO4, features = top10$gene) + NoLegend()
DimPlot(SO4)

markerstoplot <- c("Pappa2", "Egf", "Jun","S100g","Cxcl10")

DotPlot(SO4,
features = markerstoplot,
dot.scale = 8,
dot.min = 0,
scale = FALSE,
scale.max = 100,
scale.min = 0,
col.min = -2.5,
col.max = 2.5)+
coord_flip()



```

# Visualizing the DEG's in each cluster

```{r}
VlnPlot(SO4,"S100g")
VlnPlot(SO4,"Cxcl10")
VlnPlot(SO4,"Fos")
VlnPlot(SO4,"Egf")
VlnPlot(SO4,"Pappa2")
```

```{r}

save(SO4, file = here("jk_code", "JK_remove_mtrpgm.rds"))

```

