---
title: "Low salt Vs Control"
author: "jeff karnsomprot"
date: "2025-06-29"
output:
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: yes
    theme: journal
    df_print: paged
    code_folding: hide
    highlight: pygments
---

# Loading in Data sets + Library packages.

```{r load new packages, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

options(repos = c(CRAN = "https://cloud.r-project.org"))
if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!requireNamespace('BiocManager', quietly = TRUE)) {install.packages('BiocManager'); require("BiocManager")}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("stringr")) {install.packages("stringr"); require("stringr")}
if (!require("Seurat")) {install.packages("Seurat"); require("Seurat")}
if (!require("sctransform")) {install.packages("sctransform"); require("sctransform")}
if (!require("glmGamPoi")) {BiocManager::install('glmGamPoi'); require("glmGamPoi")}
if (!require("patchwork")) {install.packages("patchwork"); require("patchwork")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("EnhancedVolcano")) {BiocManager::install('EnhancedVolcano'); require("EnhancedVolcano")}
if (!require("DESeq2")) {BiocManager::install('DESeq2'); require("DESeq2")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")}
if (!require("RColorBrewer")) {install.packages("RColorBrewer"); require("RColorBrewer")}
if (!require("car")) {install.packages("car"); require("car")}
if (!require("openxlsx")) {install.packages("openxlsx"); require("openxlsx")}
if (!require("readxl")) {install.packages("readxl"); require("readxl")}
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")}
if (!require("gghighlight")) {install.packages("gghighlight"); require("gghighlight")}
if (!require("ggpmisc")) {install.packages("ggpmisc"); require("ggpmisc")}
if (!require("data.table")) {install.packages("data.table"); require("data.table")}
if (!require("here")) {install.packages("here"); require("here")}
if (!require("clusterProfiler")) {BiocManager::install('clusterProfiler'); require("clusterProfiler")}
if (!require("enrichplot")) {BiocManager::install('enrichplot'); require("enrichplot")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")} # for data frame transformation
if (!require("gplots")) {install.packages("gplots"); require("gplots")}
if (!require("ggvenn")) {install.packages("ggvenn"); require("ggvenn")}
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")}

# Install from scratch
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("RSQLite")  # Core dependency
BiocManager::install("org.Mm.eg.db")
BiocManager::install("clusterProfiler")


# CRAN packages
install.packages(c("dplyr", "magrittr"))
library(org.Mm.eg.db)
library(clusterProfiler)
library(AnnotationDbi)
library(dplyr)
library(magrittr)




library("EnhancedVolcano")
library(UpSetR)

```


# Loading Dataset

```{r}
options(future.globals.maxSize = 74 * 1024^3) # 55 GB
getOption("future.globals.maxSize") #59055800320
```

```{r}

load(here("jk_code", "JK_clean_MD.rds"))
```


```{r}

Idents(SO4) <- "subclass2_MD"

SO4$sample <- factor(SO4$sample, levels = c("SO1", "SO4", "SO3", "SO2"))

VlnPlot(SO4,"S100g",split.by = "treatment",group.by = "sample")

# Macula Densa Markers , Nos1, Avpr1a, Slc12a1, Ptgs2, and Slc9a2

VlnPlot(SO4, c("Nos1","Avpr1a","Slc12a1","Ptgs2","Slc9a2","Pappa2"),split.by = "treatment",group.by = "treatment")

DimPlot(SO4)

SO4 <- SO4[
  !grepl("^(mt-|Rp|Gm)|Rik$", rownames(SO4)),
  ,
  drop = FALSE
]

DimPlot(SO4,group.by = "treatment",split.by = "treatment")

#compare each type 1 control to type 1 low_treatment

```

# Markers of control vs low_salt up/down regulation
 
 Upregulated = low salt, positive, activated by low_salt
 Downregulated = control, negative, supressed of low_salt
 
 
```{r}

VlnPlot(SO4, features = "Pappa2", group.by = "treatment", split.by = "subclass_MD")


DimPlot(SO4, reduction = "umap", split.by = "treatment", label = TRUE)


```


```{R}

Idents(SO4) <- "treatment"

type_markers <- FindMarkers(
  object = SO4,
  ident.1 = "low_salt",   
  ident.2 = "control",     
  group.by = "treatment",
  min.pct = 0.1,           
  logfc.threshold = 0.1,  
  only.pos = FALSE         
)

 type_markers$gene <- rownames(type_markers)
 
type_markers <-type_markers %>% arrange(desc(avg_log2FC))
 

```

##  Pathway Upregulated = Low salt 

```{r}

df<- type_markers 


df2 <- df %>% filter(p_val_adj < 0.05)


DEG_list <- df2

markers1up <- DEG_list %>% rownames_to_column(var="SYMBOL")


ENTREZ_list <- bitr(
  geneID = rownames(DEG_list),
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Mm.eg.db
)

markers1up <-  ENTREZ_list %>% inner_join(markers1up, by = "SYMBOL")

markers1up <-  markers1up %>% dplyr::filter(p_val_adj < 0.05)
#head(markers, n = 50)

pos.markers1up <-  markers1up %>% dplyr::filter(avg_log2FC > 0.3) %>%  arrange(desc(abs(avg_log2FC))) 
#change around avg log value 

pos.ranks1up <- pos.markers1up$ENTREZID[abs(pos.markers1up$avg_log2FC) > 0]
#head(pos.ranks)

pos_go1up <- enrichGO(gene = pos.ranks1up,           #a vector of entrez gene id
                   OrgDb = "org.Mm.eg.db",    
                   ont = "BP",
                   readable = TRUE)              #whether mapping gene ID to gene Name

pos_go1up

 chart1up <- dotplot(pos_go1up) +
    ggtitle("upregulated lowsalt") +
    theme_classic() + 
    theme(
        plot.title = element_text(hjust = 0.5),
        legend.position = "left",
        axis.text.y = element_text(hjust = 0, size = 10)) +
    scale_y_discrete(position = "right", 
                     labels = function(x) str_wrap(x, width = 25))  # Wrap y-axis labels to 2 lines
 

chart1up

```


## Downregulation Pathway

```{r}

# Arrange and filter DEGs

df <- type_markers %>% arrange(desc(avg_log2FC))

df2 <- df %>% filter(p_val_adj < 0.05)

DEG_list <- df2

markers1down <- DEG_list %>% rownames_to_column(var="SYMBOL")

ENTREZ_list <- bitr(
  geneID = rownames(DEG_list),
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Mm.eg.db
)

markers1down <- ENTREZ_list %>% inner_join(markers1down, by = "SYMBOL")

markers1down <- markers1down %>% dplyr::filter(p_val_adj < 0.05)

pos.markers1down <- markers1down %>% dplyr::filter(avg_log2FC < 0) %>% arrange(desc(abs(avg_log2FC)))

pos.ranks1down <- pos.markers1down$ENTREZID[abs(pos.markers1down$avg_log2FC) > 0.35]

# GO enrichment for downregulated genes
pos_go1down <- enrichGO(
  gene = pos.ranks1down,
  OrgDb = org.Mm.eg.db,
  ont = "BP",
  readable = TRUE
)

pos_go1down

# Visualization
chart1down <- dotplot(pos_go1down) +
  ggtitle("downregulated control") +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "left",
    axis.text.y = element_text(hjust = 0, size = 10)
  ) +
  scale_y_discrete(
    position = "right",
    labels = function(x) str_wrap(x, width = 25)
  )

chart1down

```
```{r}

pathway_list <- list(
  "Upreg-Low Salt" = pos_go1up@result,
  "Downreg-Control" = pos_go1down@result
)


wb <- createWorkbook()


for (sheet_name in names(pathway_list)) {
  addWorksheet(wb, sheet_name)
  writeData(wb, sheet_name, pathway_list[[sheet_name]])
}

# Save the workbook
saveWorkbook(wb, here("jk_code", "Treatment_MD_DEGs.xlsx"), overwrite = TRUE)


```
